export const GET_DBA_LISTING_DATA = "GET_DBA_LISTING_DATA";
export const GET_DBA_LISTING_DATA_SUCCESS = "GET_DBA_LISTING_DATA_SUCCESS";
export const HIDE_BOOKING_MESSAGE = "HIDE_BOOKING_MESSAGE";
export const GET_DBA_DATA_ERROR = "GET_DBA_DATA_ERROR";
export const SHOW_BOOKING_MESSAGE = "SHOW_BOOKING_MESSAGE";
export const SAVE_DELIVERY_DETAILS = "SAVE_DELIVERY_DETAILS";
export const SAVE_PICKUP_DETAILS = "SAVE_PICKUP_DETAILS";
export const SAVE_NEW_BOOKING = "SAVE_NEW_BOOKING";
export const BOOKING_ERROR = "BOOKING_ERROR";
export const BOOKING_SUCCESS = "BOOKING_SUCCESS";
export const UPDATE_BOOKING = "UPDATE_BOOKING";
export const BOOKING_UPDATE_SUCCESS = "BOOKING_UPDATE_SUCCESS";
export const GET_BOOKINGS = "GET_BOOKINGS";
export const BOOKINGS_SUCCESS = "BOOKINGS_SUCCESS";
export const BOOKINGS_ERROR = "BOOKINGS_ERROR";
export const RESET_BOOKING_DATA = "RESET_BOOKING_DATA";
export const DELETE_BOOKING = "DELETE_BOOKING";
export const BOOKING_DELETE_SUCCESS = "BOOKING_DELETE_SUCCESS";
export const SHOW_BOOKING_LIST_MESSAGE = "SHOW_BOOKING_LIST_MESSAGE";
export const HIDE_BOOKING_LIST_MESSAGE = "HIDE_BOOKING_LIST_MESSAGE";
export const ADD_BOOKING_ITEM = "ADD_BOOKING_ITEM";
export const REMOVE_BOOKING_ITEM = "REMOVE_BOOKING_ITEM";
export const ADD_TAG_TO_BOOKING_ITEM = "ADD_TAG_TO_BOOKING_ITEM";
export const REMOVE_TAG_TO_BOOKING_ITEM = "REMOVE_TAG_TO_BOOKING_ITEM";



